# Based on blog post https://medium.freecodecamp.org/how-to-stop-errors-before-they-ever-hit-your-codebase-with-travis-ci-and-eslint-7a5a6b1fcd4a

language: node_js

node_js:
  - '8'
  - '10'
  - '11'

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

cache:
  directories:
    - node_modules

sudo: false

script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $PHYLOREFBOT_GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  committer_from_gh: true
  on:
    branch: master
